// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
	integrations: [
		starlight({
			title: {
				'zh-CN': 'Codex 指南手册',
				en: 'Codex Handbook',
			},
			customCss: ['./src/styles/custom.css'],
			components: {
				PageFrame: './src/components/PageFrame.astro',
				Footer: './src/components/Footer.astro',
				ThemeSelect: './src/components/ThemeSelect.astro',
				LanguageSelect: './src/components/LanguageSelect.astro',
			},
			defaultLocale: 'root',
			locales: {
				root: {
					label: '简体中文',
					lang: 'zh-CN',
				},
				en: { label: 'English', lang: 'en' },
				'zh-tw': { label: '繁體中文', lang: 'zh-TW' },
				fr: { label: 'Français', lang: 'fr' },
				ja: { label: '日本語', lang: 'ja' },
				ko: { label: '한국어', lang: 'ko' },
			},
			social: [
				{
					icon: 'github',
					label: 'GitHub',
					href: 'https://github.com/cyberhope/codex-handbook',
				},
			],
			sidebar: [
				{
					label: '从这里开始',
					translations: { en: 'Start here' },
					items: [
						{ slug: '00-start-here' },
						{ slug: '00-start-here/what-is-codex' },
						{ slug: '00-start-here/who-is-this-handbook-for' },
						{ slug: '00-start-here/choose-your-path' },
						{ slug: '00-start-here/codex-capability-map' },
						{ slug: '00-start-here/prerequisites' },
						{ slug: '00-start-here/terminology-for-beginners' },
						{ slug: '00-start-here/handbook-version-policy' },
					],
				},
				{
					label: '基础概念',
					translations: { en: 'Foundations' },
					items: [
						{ slug: '01-foundations' },
						{ slug: '01-foundations/ai-and-language-models' },
						{ slug: '01-foundations/agent-basics' },
						{ slug: '01-foundations/goals-context-and-actions' },
						{ slug: '01-foundations/files-tools-and-commands' },
						{ slug: '01-foundations/local-vs-cloud' },
						{ slug: '01-foundations/threads-tasks-and-projects' },
						{ slug: '01-foundations/permissions-and-approvals' },
						{ slug: '01-foundations/sandbox-and-network' },
						{ slug: '01-foundations/models-and-reasoning' },
						{ slug: '01-foundations/tokens-context-and-compaction' },
						{ slug: '01-foundations/verification-and-human-review' },
						{ slug: '01-foundations/common-misconceptions' },
					],
				},
				{
					label: '快速上手',
					translations: { en: 'Getting started' },
					items: [
						{ slug: '02-getting-started' },
						{ slug: '02-getting-started/account-plans-and-access' },
						{ slug: '02-getting-started/choose-your-codex-client' },
						{ slug: '02-getting-started/install-desktop-app' },
						{ slug: '02-getting-started/install-cli' },
						{ slug: '02-getting-started/install-ide-extension' },
						{ slug: '02-getting-started/sign-in-and-authentication' },
						{ slug: '02-getting-started/create-your-first-project' },
						{ slug: '02-getting-started/run-your-first-task' },
						{ slug: '02-getting-started/review-the-result' },
						{ slug: '02-getting-started/undo-and-recover' },
						{ slug: '02-getting-started/first-30-minutes' },
						{ slug: '02-getting-started/beginner-safety-checklist' },
					],
				},
				{
					label: '学习路径',
					translations: { en: 'Learning paths' },
					items: [
						{ slug: '03-learning-paths' },
						{
							label: '初学者',
							translations: { en: 'Beginner' },
							items: [
								{ slug: '03-learning-paths/beginner/01-talk-to-codex' },
								{ slug: '03-learning-paths/beginner/02-work-with-files' },
								{ slug: '03-learning-paths/beginner/03-give-clear-tasks' },
								{ slug: '03-learning-paths/beginner/04-review-results' },
								{ slug: '03-learning-paths/beginner/05-complete-first-project' },
							],
						},
						{ slug: '03-learning-paths/creator' },
						{ slug: '03-learning-paths/developer' },
						{ slug: '03-learning-paths/team' },
					],
				},
				{
					label: '产品手册',
					translations: { en: 'Product guides' },
					items: [
						{ slug: '04-product-guides' },
						{
							label: '桌面 App',
							translations: { en: 'Desktop App' },
							items: [
								{ slug: '04-product-guides/desktop-app' },
								{ slug: '04-product-guides/desktop-app/installation-and-interface' },
								{ slug: '04-product-guides/desktop-app/projects-and-tasks' },
								{ slug: '04-product-guides/desktop-app/parallel-agents' },
								{ slug: '04-product-guides/desktop-app/worktrees' },
								{ slug: '04-product-guides/desktop-app/diffs-comments-and-review' },
								{ slug: '04-product-guides/desktop-app/integrated-terminal' },
								{ slug: '04-product-guides/desktop-app/local-and-cloud-tasks' },
								{ slug: '04-product-guides/desktop-app/notifications' },
								{ slug: '04-product-guides/desktop-app/settings' },
								{ slug: '04-product-guides/desktop-app/troubleshooting' },
							],
						},
						{
							label: 'CLI',
							translations: { en: 'CLI' },
							items: [
								{ slug: '04-product-guides/cli' },
								{ slug: '04-product-guides/cli/installation-and-updates' },
								{ slug: '04-product-guides/cli/interactive-mode' },
								{ slug: '04-product-guides/cli/non-interactive-mode' },
								{ slug: '04-product-guides/cli/configuration' },
								{ slug: '04-product-guides/cli/commands-and-shortcuts' },
								{ slug: '04-product-guides/cli/approvals-and-sandbox' },
								{ slug: '04-product-guides/cli/troubleshooting' },
							],
						},
						{
							label: 'IDE',
							translations: { en: 'IDE' },
							items: [
								{ slug: '04-product-guides/ide' },
								{ slug: '04-product-guides/ide/supported-editors' },
								{ slug: '04-product-guides/ide/installation' },
								{ slug: '04-product-guides/ide/editor-context' },
								{ slug: '04-product-guides/ide/selected-code-and-open-files' },
								{ slug: '04-product-guides/ide/local-task-workflow' },
								{ slug: '04-product-guides/ide/cloud-task-workflow' },
								{ slug: '04-product-guides/ide/reviewing-changes' },
								{ slug: '04-product-guides/ide/settings' },
								{ slug: '04-product-guides/ide/troubleshooting' },
							],
						},
						{
							label: 'Web 与 Cloud',
							translations: { en: 'Web & Cloud' },
							items: [
								{ slug: '04-product-guides/web-and-cloud' },
								{ slug: '04-product-guides/web-and-cloud/connect-github' },
								{ slug: '04-product-guides/web-and-cloud/cloud-environments' },
								{ slug: '04-product-guides/web-and-cloud/secrets-and-variables' },
								{ slug: '04-product-guides/web-and-cloud/internet-access' },
								{ slug: '04-product-guides/web-and-cloud/create-pull-requests' },
								{ slug: '04-product-guides/web-and-cloud/code-review' },
								{ slug: '04-product-guides/web-and-cloud/delegate-and-follow-up' },
								{ slug: '04-product-guides/web-and-cloud/troubleshooting' },
							],
						},
						{ slug: '04-product-guides/mobile-and-remote' },
						{
							label: '集成',
							translations: { en: 'Integrations' },
							items: [
								{ slug: '04-product-guides/integrations' },
								{ slug: '04-product-guides/integrations/github' },
							],
						},
					],
				},
				{
					label: '核心能力',
					translations: { en: 'Core capabilities' },
					items: [
						{ slug: '05-core-capabilities' },
						{
							label: '提示词',
							translations: { en: 'Prompting' },
							items: [
								{ slug: '05-core-capabilities/prompting' },
								{ slug: '05-core-capabilities/prompting/prompt-basics' },
								{ slug: '05-core-capabilities/prompting/anatomy-of-a-good-task' },
								{ slug: '05-core-capabilities/prompting/provide-goals-and-context' },
								{ slug: '05-core-capabilities/prompting/define-constraints' },
								{ slug: '05-core-capabilities/prompting/define-done' },
								{ slug: '05-core-capabilities/prompting/ask-for-a-plan' },
								{ slug: '05-core-capabilities/prompting/iterative-prompting' },
								{ slug: '05-core-capabilities/prompting/prompting-with-images' },
								{ slug: '05-core-capabilities/prompting/prompting-for-long-tasks' },
								{ slug: '05-core-capabilities/prompting/prompting-anti-patterns' },
								{ slug: '05-core-capabilities/prompting/prompt-debugging' },
							],
						},
						{
							label: '上下文',
							translations: { en: 'Context' },
							items: [
								{ slug: '05-core-capabilities/context' },
								{ slug: '05-core-capabilities/context/project-context' },
								{ slug: '05-core-capabilities/context/file-and-folder-context' },
								{ slug: '05-core-capabilities/context/conversation-context' },
								{ slug: '05-core-capabilities/context/context-priority' },
								{ slug: '05-core-capabilities/context/compaction' },
								{ slug: '05-core-capabilities/context/keep-context-focused' },
								{ slug: '05-core-capabilities/context/sensitive-context' },
							],
						},
						{
							label: '质量与验证',
							translations: { en: 'Quality & verification' },
							items: [
								{ slug: '05-core-capabilities/quality' },
								{ slug: '05-core-capabilities/quality/review-diffs' },
								{ slug: '05-core-capabilities/quality/run-tests' },
								{ slug: '05-core-capabilities/quality/verify-artifacts' },
								{ slug: '05-core-capabilities/quality/validate-sources' },
								{ slug: '05-core-capabilities/quality/handle-uncertainty' },
								{ slug: '05-core-capabilities/quality/definition-of-done' },
							],
						},
						{
							label: '文件与产物',
							translations: { en: 'Files & artifacts' },
							items: [
								{ slug: '05-core-capabilities/files-and-artifacts' },
								{ slug: '05-core-capabilities/files-and-artifacts/text-and-code-files' },
								{ slug: '05-core-capabilities/files-and-artifacts/images-and-screenshots' },
								{ slug: '05-core-capabilities/files-and-artifacts/pdf-and-documents' },
								{ slug: '05-core-capabilities/files-and-artifacts/tables-and-spreadsheets' },
								{ slug: '05-core-capabilities/files-and-artifacts/presentations' },
								{ slug: '05-core-capabilities/files-and-artifacts/generated-artifacts' },
							],
						},
						{
							label: '工具',
							translations: { en: 'Tools' },
							items: [
								{ slug: '05-core-capabilities/tools' },
								{ slug: '05-core-capabilities/tools/tool-selection' },
								{ slug: '05-core-capabilities/tools/shell-and-terminal' },
								{ slug: '05-core-capabilities/tools/web-search' },
								{ slug: '05-core-capabilities/tools/browser' },
								{ slug: '05-core-capabilities/tools/computer-use' },
								{ slug: '05-core-capabilities/tools/image-generation' },
								{ slug: '05-core-capabilities/tools/voice' },
							],
						},
						{
							label: 'Agent 工作',
							translations: { en: 'Agent work' },
							items: [
								{ slug: '05-core-capabilities/agent-work' },
								{ slug: '05-core-capabilities/agent-work/planning' },
								{ slug: '05-core-capabilities/agent-work/subagents' },
								{ slug: '05-core-capabilities/agent-work/progress-and-steering' },
								{ slug: '05-core-capabilities/agent-work/handoff-and-resume' },
							],
						},
					],
				},
				{
					label: '个性化配置',
					translations: { en: 'Customization' },
					items: [
						{ slug: '06-customization' },
						{
							label: 'AGENTS.md',
							translations: { en: 'AGENTS.md' },
							items: [
								{ slug: '06-customization/agents-md/what-is-agents-md' },
								{ slug: '06-customization/agents-md/scope-and-precedence' },
								{ slug: '06-customization/agents-md/writing-effective-instructions' },
							],
						},
						{ slug: '06-customization/project-instructions' },
						{ slug: '06-customization/memories-and-persistent-context' },
						{ slug: '06-customization/configuration/config-basics' },
						{ slug: '06-customization/configuration/profiles' },
						{ slug: '06-customization/personal-preferences' },
						{
							label: '规则',
							translations: { en: 'Rules' },
							items: [
								{ slug: '06-customization/rules/allow-and-deny-patterns' },
								{ slug: '06-customization/rules/command-rules' },
								{ slug: '06-customization/rules/team-rules' },
							],
						},
						{ slug: '06-customization/examples/monorepo-agents-md' },
					],
				},
				{
					label: '扩展与自动化',
					translations: { en: 'Extensions' },
					items: [
						{ slug: '07-extensions-automation' },
						{ slug: '07-extensions-automation/capability-map' },
						{ slug: '07-extensions-automation/choosing-an-extension-method' },
						{
							label: 'Skills',
							translations: { en: 'Skills' },
							items: [
								{ slug: '07-extensions-automation/skills/skills-overview' },
								{ slug: '07-extensions-automation/skills/create-your-first-skill' },
								{ slug: '07-extensions-automation/skills/skill-security-and-versioning' },
							],
						},
						{
							label: 'MCP',
							items: [
								{ slug: '07-extensions-automation/mcp/mcp-overview' },
								{ slug: '07-extensions-automation/mcp/connect-an-mcp-server' },
								{ slug: '07-extensions-automation/mcp/debugging-mcp' },
							],
						},
						{
							label: 'Hooks',
							items: [
								{ slug: '07-extensions-automation/hooks/hooks-overview' },
								{ slug: '07-extensions-automation/hooks/hook-event-types' },
								{ slug: '07-extensions-automation/hooks/hooks-examples' },
							],
						},
						{ slug: '07-extensions-automation/plugins/plugins-overview' },
						{ slug: '07-extensions-automation/automations/scheduled-tasks' },
					],
				},
				{
					label: '开发者平台',
					translations: { en: 'Developer platform' },
					items: [
						{ slug: '08-developer-platform' },
						{ slug: '08-developer-platform/sdk-overview' },
						{
							label: '非交互',
							translations: { en: 'Non-interactive' },
							items: [
								{ slug: '08-developer-platform/non-interactive/codex-exec' },
								{ slug: '08-developer-platform/non-interactive/scripts-and-pipelines' },
								{ slug: '08-developer-platform/non-interactive/structured-output' },
								{ slug: '08-developer-platform/non-interactive/exit-codes-and-retries' },
							],
						},
						{
							label: 'Webhooks',
							items: [
								{ slug: '08-developer-platform/webhooks/overview' },
							],
						},
						{
							label: 'CI/CD',
							items: [
								{ slug: '08-developer-platform/ci-cd/code-review-automation' },
							],
						},
					],
				},
				{
					label: '工作流方法',
					translations: { en: 'Workflows' },
					items: [
						{ slug: '09-workflows' },
						{ slug: '09-workflows/explore-plan-execute-verify' },
						{ slug: '09-workflows/brainstorm-before-building' },
						{ slug: '09-workflows/specification-driven-work' },
						{ slug: '09-workflows/test-driven-work' },
						{ slug: '09-workflows/diagnose-before-fixing' },
						{ slug: '09-workflows/review-before-merge' },
						{ slug: '09-workflows/research-with-sources' },
						{ slug: '09-workflows/artifact-first-work' },
						{ slug: '09-workflows/multi-agent-coordination' },
						{ slug: '09-workflows/long-running-task-management' },
						{ slug: '09-workflows/human-approval-patterns' },
						{ slug: '09-workflows/failure-recovery' },
						{ slug: '09-workflows/turn-a-workflow-into-a-skill' },
					],
				},
				{
					label: '场景案例',
					translations: { en: 'Use cases' },
					items: [
						{ slug: '10-use-cases' },
						{ slug: '10-use-cases/case-study-template' },
						{
							label: '软件开发',
							translations: { en: 'Software development' },
							items: [
								{ slug: '10-use-cases/software-development/fix-a-bug-with-verification' },
							],
						},
						{
							label: '内容创作',
							translations: { en: 'Content creation' },
							items: [
								{ slug: '10-use-cases/content-creation/refactor-docs-with-review' },
							],
						},
						{
							label: '研究与学习',
							translations: { en: 'Research & learning' },
							items: [
								{ slug: '10-use-cases/research-and-learning/competitive-feature-matrix' },
							],
						},
						{
							label: '团队自动化',
							translations: { en: 'Team automation' },
							items: [
								{ slug: '10-use-cases/team-automation/scheduled-link-check' },
								{ slug: '10-use-cases/team-automation/issue-triage-suggestions' },
							],
						},
					],
				},
				{
					label: '团队与企业',
					translations: { en: 'Team & enterprise' },
					items: [
						{ slug: '11-team-enterprise' },
						{
							label: '安全',
							translations: { en: 'Security' },
							items: [
								{ slug: '11-team-enterprise/security/threat-model' },
								{ slug: '11-team-enterprise/security/plugin-and-mcp-risk' },
								{ slug: '11-team-enterprise/security/prompt-injection' },
							],
						},
						{
							label: '治理',
							translations: { en: 'Governance' },
							items: [
								{ slug: '11-team-enterprise/governance/acceptable-use' },
							],
						},
					],
				},
				{
					label: '参考资料',
					translations: { en: 'Reference' },
					items: [
						{ slug: '12-reference' },
						{ slug: '12-reference/glossary' },
						{ slug: '12-reference/faq' },
						{ slug: '12-reference/feature-comparison' },
						{ slug: '12-reference/commands' },
						{ slug: '12-reference/slash-commands' },
						{ slug: '12-reference/configuration-reference' },
						{ slug: '12-reference/permission-matrix' },
						{ slug: '12-reference/environment-variables' },
						{ slug: '12-reference/keyboard-shortcuts' },
						{ slug: '12-reference/error-reference' },
						{ slug: '12-reference/troubleshooting' },
						{ slug: '12-reference/official-resources' },
					],
				},
				{
					label: '参与贡献',
					translations: { en: 'Contributing' },
					items: [
						{ slug: '13-contributing' },
						{ slug: '13-contributing/write-a-guide' },
						{ slug: '13-contributing/add-a-prompt-example' },
						{ slug: '13-contributing/verify-technical-content' },
					],
				},
			],
		}),
	],
});
