import type { SidebarEntry } from '@astrojs/starlight/utils/routing/types';

/** Fallback labels for directories that have no index.md. */
const GROUP_LABELS: Record<string, string> = {
	'agents-md': 'AGENTS.md',
	beginner: '初学者路径',
	'ci-cd': 'CI/CD',
	configuration: '配置',
	examples: '示例',
	governance: '治理',
	'non-interactive': '非交互模式',
	rules: '规则',
	security: '安全',
	webhooks: 'Webhooks',
};

const OVERVIEW_LABELS: Record<string, string> = {
	root: '概览',
	en: 'Overview',
	'zh-tw': '概覽',
	fr: 'Vue d’ensemble',
	ja: '概要',
	ko: '개요',
	es: 'Resumen',
	de: 'Übersicht',
	pt: 'Visão geral',
	vi: 'Tổng quan',
};

function localeFromHref(href: string): string {
	const firstSegment = href.split('/').filter(Boolean)[0];
	return firstSegment && firstSegment in OVERVIEW_LABELS ? firstSegment : 'root';
}

function isIndexLink(href: string, dirName: string): boolean {
	const normalized = href.replace(/\/$/, '');
	return normalized.endsWith(`/${dirName}`);
}

function overviewLink(entry: Extract<SidebarEntry, { type: 'link' }>): SidebarEntry {
	return { ...entry, label: OVERVIEW_LABELS[localeFromHref(entry.href)] ?? OVERVIEW_LABELS.root };
}

function labelForGroup(entry: Extract<SidebarEntry, { type: 'group' }>): string {
	const indexLink = entry.entries.find(
		(child): child is Extract<SidebarEntry, { type: 'link' }> =>
			child.type === 'link' && isIndexLink(child.href, entry.label),
	);
	if (indexLink) return indexLink.label;
	return GROUP_LABELS[entry.label] ?? entry.label;
}

/** Replace autogenerated English directory names with page titles from index links. */
export function localizeSidebarLabels(entries: SidebarEntry[]): SidebarEntry[] {
	return entries.map((entry) => {
		if (entry.type === 'link') return entry;

		const children = localizeSidebarLabels(entry.entries);
		const label = labelForGroup({ ...entry, entries: children });
		const indexLink = children.find(
			(child): child is Extract<SidebarEntry, { type: 'link' }> =>
				child.type === 'link' && isIndexLink(child.href, entry.label),
		);
		const nextChildren =
			indexLink && children.length > 1
				? [overviewLink(indexLink), ...children.filter((child) => child !== indexLink)]
				: children;

		return { ...entry, label, entries: nextChildren };
	});
}
